name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipywidgets
  - nbformat<=5.5.0  # https://github.com/jupyterlite/xeus-python-kernel/issues/120
  - numpy
  - conda-forge::plotly>=5.12.0
